name: Maven Pull Request Sonar Test

on:
  workflow_run:
    workflows: [Maven Pull Request Build]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Debug Print GitHub Context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          
      - name: Debug Print Github Event
        run: echo '${{ github.event.workflow_run.event }}'
          
      - uses: actions/checkout@v3
        with:
            repository: '${{ github.event.workflow_run.head_repository.full_name }}'
            ref: '${{ github.event.workflow_run.head_branch }}'

      - name: Test with Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify -P coverage sonar:sonar
          -Dsonar.projectKey=FraunhoferIOSB_FAAAST-Package-Explorer-Converter
          -Dsonar.pullrequest.key=10
          -Dsonar.pullrequest.branch='${{ github.event.workflow_run.head_branch }}'
          -Dmaven.javadoc.skip=true

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      
